// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: pkg/proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlPlane_Connect_FullMethodName = "/uptimy.agent.v1.AgentControlPlane/Connect"
)

// AgentControlPlaneClient is the client API for AgentControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControlPlane is the bidirectional streaming service between
// the Uptimy Agent and the control plane.
type AgentControlPlaneClient interface {
	// Connect opens a persistent bidirectional stream.
	// The agent sends telemetry and receives configuration updates.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type agentControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlPlaneClient(cc grpc.ClientConnInterface) AgentControlPlaneClient {
	return &agentControlPlaneClient{cc}
}

func (c *agentControlPlaneClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlPlane_ServiceDesc.Streams[0], AgentControlPlane_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlane_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// AgentControlPlaneServer is the server API for AgentControlPlane service.
// All implementations must embed UnimplementedAgentControlPlaneServer
// for forward compatibility.
//
// AgentControlPlane is the bidirectional streaming service between
// the Uptimy Agent and the control plane.
type AgentControlPlaneServer interface {
	// Connect opens a persistent bidirectional stream.
	// The agent sends telemetry and receives configuration updates.
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedAgentControlPlaneServer()
}

// UnimplementedAgentControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlPlaneServer struct{}

func (UnimplementedAgentControlPlaneServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentControlPlaneServer) mustEmbedUnimplementedAgentControlPlaneServer() {}
func (UnimplementedAgentControlPlaneServer) testEmbeddedByValue()                           {}

// UnsafeAgentControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlPlaneServer will
// result in compilation errors.
type UnsafeAgentControlPlaneServer interface {
	mustEmbedUnimplementedAgentControlPlaneServer()
}

func RegisterAgentControlPlaneServer(s grpc.ServiceRegistrar, srv AgentControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedAgentControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlPlane_ServiceDesc, srv)
}

func _AgentControlPlane_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlPlaneServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlane_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// AgentControlPlane_ServiceDesc is the grpc.ServiceDesc for AgentControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uptimy.agent.v1.AgentControlPlane",
	HandlerType: (*AgentControlPlaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentControlPlane_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/agent.proto",
}
